landing and responsiveness
feedback-news/feedback-main pull request #190
Opened 2020-11-18 10:54 UTC by mathieuabeille

2020-11-18 11:18 UTC, tdquan requested changes
I think you probably need to set up your eslint on local to check for errors so that your PR can pass all the netlify tests :)

2020-11-18 11:18 UTC, tdquan commented on webapp/src/selectors/selectVisibleLinksByComponentName.js
> +    visible: () => false
I already took care of this with a feature flag so you don't have to change it to False

2020-11-18 11:18 UTC, tdquan commented on webapp/src/styles/components/pages/_Landing.scss
> +    .heroContent{
this should be changed to `hero-content` to be consistent with current naming convention

2020-11-18 11:18 UTC, tdquan commented on webapp/src/styles/global/_button.scss
> +  text-decoration: none;
I think Erwan will nag you about having these alphabetically-sorted ;) also, please watch out for indentation

2020-11-18 11:23 UTC, mathieuabeille commented on webapp/src/styles/components/pages/_Landing.scss
> +    .heroContent{
@tdquan  Thanks

2020-11-20 12:56 UTC, Ledoux requested changes

2020-11-20 12:56 UTC, Ledoux commented on api/alembic/versions/14edc960a62e_create_platform_table.py
> -                              auto_increment=True,
I think this change  should be removed from this branch, it has no relation and we still want to make the id as an autoincrement column.

2020-11-20 12:56 UTC, Ledoux commented on api/domain/googleapi.py
> +import requests
I would like that you save this in another branch, and a PR related to the associated Kanban ticket, please.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/components/layout/Header/index.jsx
> +    <header className={classnames('header')}>
if you removed the is-blurred condition class, then you can directly write:
```
<header className='header' />
```

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/components/pages/Verdict/TestifierDashboard/Tabs.jsx
> +    isDisplayedFrom: () => false,
You don't need this line as the https://github.com/feedback-news/feedback-main/blob/master/webapp/src/components/pages/Verdict/TestifierDashboard/Tabs.jsx#L46 line will take of it becaus eof your features activated or not.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/selectors/selectVisibleLinksByComponentName.js
> +    visible: () => false
Same

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +    color: #202438;
put it in alphabetical order please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +    color: #202438;
can you use a $<your color name> variable, please ?
if #202438 is not in the webapp/src/styles/variables/_colors.scss
you can invent a name for it 
```
$<your color name>:       #202438;

```

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +      color: #202438;
same use a $<your color name variable>

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +    color: #202438;
Or you can resue one color variable also to not so much extend the palette, if it is not a big need.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +      height: 1.953rem;
choose a 1.875rem or 2rem please.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Feeds/Controls/_KeywordsBar.scss
> +@media only screen and (min-width: 400px) {
you can remove screen option.
Please create a variable in webapp/src/styles/variables/_breakpoints.scss 
$phone: 400px;
and use it here.

Also please include your block in 
```
  .keywords-input { 
     ...stuff

    @media(min-width: $phone) {
         font-size: 1rem;
         height: 2.5rem;
   }
}

```

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Header/Menu/index.scss
> +@media only screen and (min-width: 400px) {
same, include nested in the definitiions above please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Header/index.scss
> +    padding: 0.64rem;
0.625rem should be enough

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/Header/index.scss
> +  .header
same

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/LinkItem/_Quotation.scss
> +      font-size: 0.8rem;
alphabetical order and try also to use the variables in webapp/src/styles/variables/_typography.scss

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/LinkItem/_Quotation.scss
> +      h4 {
jump one line between color: and h4 please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/LinkItem/_Quotation.scss
> +@media only screen and (max-width: 400px) {
you can remove it

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_Avatar.scss
> +}
same to include it nested

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_VerdictItem.scss
> +  padding: 0.8rem;
jump one line please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_VerdictItem.scss
> +    align-items: center;
alphabetical order please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_VerdictItem.scss
> +    flex-direction: column;
if it is colum, then you can remove it because it is the default value for that key.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_VerdictItem.scss
> +    font-size: 0.64em;
0.625rem please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/layout/_VerdictItem.scss
> +@media only screen and (min-width: 400px) {
same as above please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_About.scss
> +.about-content {
please make it nested compared to to the parent .about class

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    z-index: 1000;
alphabetical order please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +      padding-bottom: 0.8rem;
lets try 0.75rem ?

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +      padding-bottom: 0.8rem;
or 0.825rem

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    font-size: 1.563rem;
1.625rem ?

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    font-size: 1.563rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    margin-top: 1.953rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    margin-bottom: 3.052rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    font-size: 1.563rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    margin-bottom: 1.563rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +    font-size: 0.8rem;
same as above

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/components/pages/_Landing.scss
> +@media only screen and (min-width: 400px) {
please nest this media

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/global/_button.scss
> +    padding-right: 0.64rem;
same rules for all of these please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/global/_button.scss
> +@media only screen and (min-width: 400px) {
include it nested please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/global/_columns.scss
> +      $size: 80%;
this file should not be touch, 66.66 needs to still exist for all the class names .col-#{$breakpointKey}-66

if you have a problem of width with one of your div, it is more about to change it on its specific class attached, but not here as it is a generic shared class by several layouts.

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/global/_tag.scss
> +    padding-right: 0.64rem;
alphabetical order please

2020-11-20 12:56 UTC, Ledoux commented on webapp/src/styles/global/_tag.scss
> +@media only screen and (min-width: 400px) {
nested please

2020-12-04 15:32 UTC, Ledoux commented on webapp/src/styles/components/layout/Header/index.scss
> +    padding: 0.64rem;
for later ! we need to define the grid of variables !

2020-12-04 15:58 UTC, Ledoux commented
nikel !

2020-12-04 15:58 UTC, merged